apiVersion: batch/v1
kind: Job
metadata:
  name: vocker-pv-builder
spec:
  template:
    spec:
      containers:
      - name: vocker
        image: fabiand/vocker
        command: ["vocker-job"]
        volumeMounts:
        - name: vocker-source
          mountPath: /source
        - name: target-pv
          mountPath: /target
      volumes:
#     We mount the ConfigMap as a the source
      - name: vocker-source
        configMap:
          name: vocker-source
#     We mount a PVC as the target to get all images
      - name: target-pv
        persistentVolumeClaim:
          claimName: vocker-images
#      - name: cache # would be an improvement
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
data:
  Fedora: |
    FROM fedora:23
    
    MAINTAINER "Fabian Deutsch" <fabiand@redhat.com>
    ENV container docker
    
    RUN echo Hello > /marker
    
    EXPOSE 1234
    
    CMD echo World >> /marker
